version: "3"
services:
  api:
    build: ./
    container_name: api
    depends_on:
      - database
    ports:
      - 5000:80
  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: database
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password1